### ISSUE TITLE
Can't build on Apple M1 Pro

### ISSUE THREAD

**Issue by aebanoidze** [YAtechnologies/GoogleMaps-SP#15]
Mac OS Monterey 12.0
Xcode 13.1

can't build on M1 Pro chip

<img width="920" alt="Screenshot 2021-11-10 at 20 55 51" src="https://user-images.githubusercontent.com/85483253/141157714-62f48cfc-e66a-4942-9b4f-fefccd3f2ed0.png">

**Comment by bstillitano** [comment]
Facing the exact same issue.

**Comment by karimhm** [comment]
@aebanoidze from the logs I assume that you are trying to run your application on a simulator. This happens because of an [issue](https://github.com/googlemaps/google-maps-ios-utils/issues/355) within the official *Google Maps iOS SDK* binary where it does not include a slice for *iPhone Simulator ARM64* but only *x86* and *x86_64* slice.

You may want to use the following fork [vfn/GoogleMaps-SP](https://github.com/vfn/GoogleMaps-SP) that does support the **M1** Macs made by @vfn.
